### ISSUE TITLE
Custodian Brothers - Army Issues

### ISSUE THREAD

**Issue by onepageanon** [schnick3rs/opr-web-companion#40]
- [x] Custodian Team upgrade list is broken
- [x] Custodian Assault Walker upgrade list is broken

**Comment by schnick3rs** [comment]
a) _see screenshots_
b) `Replace Spear-Rifle, Spear and 2x Destroyers:` fixed by handling *2x* items.

![image](https://user-images.githubusercontent.com/17150506/139718350-9afb4a0f-e857-4da9-8e6b-67f87d812cc7.png)

![image](https://user-images.githubusercontent.com/17150506/139718281-30b173c1-6654-43c8-aca7-ab2353d67393.png)

**Comment by schnick3rs** [comment]
@onepageanon fix deployed for "Custodian Team upgrade list is broken"
I re-calced theses. Do those numbers look correct?

![image](https://user-images.githubusercontent.com/17150506/139803601-9c238d1f-6af5-42e0-a4ba-14fa75c3e2a4.png)
